import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTableContato1778255905720 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE IF NOT EXISTS "Contato" (
                "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "codigo_pais" VARCHAR(5) NOT NULL,
                "ddd" CHAR(2) NOT NULL,
                "numero" varchar(15) NOT NULL,

                CONSTRAINT un_contanto_telefone UNIQUE ("codigo_pais", "ddd", "numero")
            )
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE IF EXISTS "Contato";`);
    }
}
