import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTableEstado1778181804054 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(
            `
                CREATE TABLE IF NOT EXISTS "Estado" (
                    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "codigoUf" INTEGER NOT NULL,
                    "name" VARCHAR(50) NOT NULL,
                    "uf" CHAR(2) NOT NULL,
                    "regiaoId" INTEGER NOT NULL,

                    FOREIGN KEY ("regiaoId") REFERENCES "Regiao" ("id")
                )
            `
        );

        await queryRunner.query(
            `
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (12, 'Acre', 'AC', 1);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (27, 'Alagoas', 'AL', 2);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (16, 'Amapá', 'AP', 1);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (13, 'Amazonas', 'AM', 1);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (29, 'Bahia', 'BA', 2);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (23, 'Ceará', 'CE', 2);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (53, 'Distrito Federal', 'DF', 5);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (32, 'Espírito Santo', 'ES', 3);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (52, 'Goiás', 'GO', 5);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (21, 'Maranhão', 'MA', 2);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (51, 'Mato Grosso', 'MT', 5);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (50, 'Mato Grosso do Sul', 'MS', 5);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (31, 'Minas Gerais', 'MG', 3);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (15, 'Pará', 'PA', 1);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (25, 'Paraíba', 'PB', 2);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (41, 'Paraná', 'PR', 4);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (26, 'Pernambuco', 'PE', 2);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (22, 'Piauí', 'PI', 2);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (33, 'Rio de Janeiro', 'RJ', 3);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (24, 'Rio Grande do Norte', 'RN', 2);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (43, 'Rio Grande do Sul', 'RS', 4);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (11, 'Rondônia', 'RO', 1);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (14, 'Roraima', 'RR', 1);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (42, 'Santa Catarina', 'SC', 4);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (35, 'São Paulo', 'SP', 3);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (28, 'Sergipe', 'SE', 2);
                insert into "Estado" ("codigoUf", "name", "uf", "regiaoId") values (17, 'Tocantins', 'TO', 1);
            `
        )
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE IF EXISTS "Estado";`)
    }

}
