import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTableLote1778527166207 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE IF NOT EXISTS "Lote" (
                "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "numero_lote" INTEGER NOT NULL,
                "preco_custo" DECIMAL NOT NULL,
                "preco_venda" DECIMAL NOT NULL,
                "localizacaoId" INTEGER NOT NULL,
                "fornecedorId" INTEGER NOT NULL,
                "data_entrada" TIMESTAMP NOT NULL,
                "data_validade" TIMESTAMP NOT NULL,
                "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                FOREIGN KEY ("localizacaoId") REFERENCES "Localizacao" ("id"),
                FOREIGN KEY ("fornecedorId") REFERENCES "Fornecedor" ("id"),

                CONSTRAINT un_lote_numero_lote_fornecedor UNIQUE ("numero_lote", "fornecedorId")
            );     
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE IF EXISTS "Lote";`);
    }
}
