import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTableFornecedor1778526059144 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE IF NOT EXISTS "Fornecedor" (
                "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "nome_empresa" VARCHAR(255) NOT NULL,
                "active" BOOLEAN NOT NULL DEFAULT true,
                "contatoId" INTEGER NOT NULL,
                "enderecoId" INTEGER NOT NULL,

                FOREIGN KEY ("contatoId") REFERENCES "Contato" ("id"),
                FOREIGN KEY ("enderecoId") REFERENCES "Endereco" ("id")
            )        
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE IF EXISTS "Fornecedor";`);
    }
}
