import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTableFuncionario1778256326183 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE IF NOT EXISTS "Funcionario" (
                "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "name" VARCHAR(50) NOT NULL,
                "email" VARCHAR(255) NOT NULL,
                "password" VARCHAR(255) NOT NULL,
                "role" VARCHAR(20) NOT NULL DEFAULT 'USER',
                "active" BOOLEAN NOT NULL DEFAULT true,
                "contatoId" INTEGER NOT NULL,
                "enderecoId" INTEGER NOT NULL,
                "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                FOREIGN KEY ("contatoId") REFERENCES "Contato" ("id"),
                FOREIGN KEY ("enderecoId") REFERENCES "Endereco" ("id"),

                CONSTRAINT un_funcionario_email UNIQUE ("email")
            )
        `);
    }

    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    public async down(queryRunner: QueryRunner): Promise<void> {}
}
