import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTableInformacoesNutricionais1778524430776 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE IF NOT EXISTS "InformacoesNutricionais" (
                "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "ingredientes" VARCHAR(255) NOT NULL,
                "alergenicos" VARCHAR(255)
            )`
        );
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE IF EXISTS "InformacoesNutricionais";`);
    }
}
