import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTableTransacoes1778526425872 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE IF NOT EXISTS "Transacoes" (
                "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "tipo" VARCHAR(20) NOT NULL DEFAULT 'ENTRADA',
                "observacao" TEXT,
                "funcionarioId" INTEGER NOT NULL,
                "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                FOREIGN KEY ("funcionarioId") REFERENCES "Funcionario" ("id")
            )
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE IF EXISTS "Transacoes";`);
    }

}
