import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTableProduto1778527172094 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE IF NOT EXISTS "Produto" (
                "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "name" VARCHAR(255) NOT NULL,
                "codigo" VARCHAR(255) NOT NULL,
                "descricao" TEXT NOT NULL,
                "active" BOOLEAN NOT NULL DEFAULT true,
                "perecivel" BOOLEAN NOT NULL DEFAULT false,
                "categoria" VARCHAR(255) NOT NULL DEFAULT 'OUTROS',
                "informacoesNutricionaisId" INTEGER,
                "unidadeMedida" VARCHAR(255) NOT NULL DEFAULT 'UN',
                "cadastrado_funcionarioId" INTEGER NOT NULL,
                "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                FOREIGN KEY ("informacoesNutricionaisId") REFERENCES "InformacoesNutricionais" ("id"),
                FOREIGN KEY ("cadastrado_funcionarioId") REFERENCES "Funcionario" ("id"),

                CONSTRAINT un_produto_codigo UNIQUE ("codigo")
            );
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE IF EXISTS "Produto";`);
    }
}
