import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTableEndereco1778255525420 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE IF NOT EXISTS "Endereco" (
                "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "logradouro" VARCHAR(50) NOT NULL,
                "numero" INTEGER NOT NULL,
                "complemento" VARCHAR(50),
                "cep" CHAR(8) NOT NULL,
                "bairroId" INTEGER NOT NULL,

                FOREIGN KEY ("bairroId") REFERENCES "Bairro" ("id")
            )
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE IF EXISTS "Endereco";`);
    }
}
