import { MigrationInterface, QueryRunner, Table } from "typeorm";

export class CreateTableRegiao1778179823637 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(
            `
                CREATE TABLE IF NOT EXISTS "Regiao" (
                    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "regiao" VARCHAR(50) NOT NULL
                );
            `
        )

        await queryRunner.query(
            `
                INSERT INTO "Regiao" ("regiao") VALUES
                    ('Norte'),
                    ('Nordeste'),
                    ('Sudeste'),
                    ('Sul'),
                    ('Centro-Oeste');
            `
        )
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE IF EXISTS "Regiao";`)
    }
}
